# supabase/config.toml (VERSÃO CORRIGIDA)

# A única linha realmente necessária para vincular o projeto é esta:
project_id = "kkzxsqsgyifxupumdszb"

# As configurações abaixo são padrões para desenvolvimento local
[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
[functions.create-recurring-transactions]
enabled = true
verify_jwt = true
import_map = "./functions/create-recurring-transactions/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-recurring-transactions/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-recurring-transactions/*.html" ]
